CREATE TABLE chats (
    id INT AUTO_INCREMENT PRIMARY KEY,
    chat_id VARCHAR(255) NOT NULL UNIQUE,
    user1 VARCHAR(255) NOT NULL,
    user2 VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_for TEXT,
    FOREIGN KEY (user1) REFERENCES users(username) ON DELETE CASCADE, 
    FOREIGN KEY (user2) REFERENCES users(username) ON DELETE CASCADE
);
